spring:
  application:
    name: SpringTask
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: task
    password: "p@ssw0rd"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  report:
    hour: 0
    minute: 29
    recipient: omarbourhani77@gmail.com
    subject: "Daily Report"
  mail:
    host: smtp.gmail.com
    port: 587
    username: omarbourhani77@gmail.com
    password: axmw drfa vbsm mkxt
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
security:
  user:
    name: test
    password: test
